CREATE TABLE [edfi].[DiplomaType] (
    [DiplomaTypeId] INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]     NVARCHAR (20)  NOT NULL,
    [Description]   NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKDiplomaTypeType] PRIMARY KEY NONCLUSTERED ([DiplomaTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UIDiplomaTypeTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);

