CREATE TABLE [edfi].[EntryType] (
    [EntryTypeId] INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]   NVARCHAR (20)  NOT NULL,
    [Description] NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKEntryTypeType] PRIMARY KEY NONCLUSTERED ([EntryTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UIEntryTypeTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);

