CREATE TABLE [edfi].[FieldType] (
    [FieldTypeId] INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]   NVARCHAR (60)  NOT NULL,
    [Description] NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKFieldType] PRIMARY KEY NONCLUSTERED ([FieldTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UIFieldTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);

