CREATE TABLE [edfi].[RaceType] (
    [RaceTypeId]  INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]   NVARCHAR (35)  NOT NULL,
    [Description] NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKRaceType] PRIMARY KEY NONCLUSTERED ([RaceTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UIRaceTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);

