CREATE TABLE [edfi].[SchoolType] (
    [SchoolTypeId] INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]    NVARCHAR (20)  NOT NULL,
    [Description]  NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKSchoolTypeType] PRIMARY KEY NONCLUSTERED ([SchoolTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UISchoolTypeTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);

