CREATE TABLE [edfi].[SexType] (
    [SexTypeId]   INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]   NVARCHAR (20)  NOT NULL,
    [Description] NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKSexType] PRIMARY KEY NONCLUSTERED ([SexTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UISexTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);

