CREATE TABLE [edfi].[TermType] (
    [TermTypeId]  INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]   NVARCHAR (20)  NOT NULL,
    [Description] NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKTermType] PRIMARY KEY NONCLUSTERED ([TermTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UITermTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IX_TermTypeCodeValue]
    ON [edfi].[TermType]([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE);

