CREATE TABLE [edfi].[WeaponsType] (
    [WeaponsTypeId] INT            IDENTITY (1, 1) NOT NULL,
    [CodeValue]     NVARCHAR (20)  NOT NULL,
    [Description]   NVARCHAR (200) NOT NULL,
    CONSTRAINT [PKWeaponsType] PRIMARY KEY NONCLUSTERED ([WeaponsTypeId] ASC) WITH (DATA_COMPRESSION = PAGE),
    CONSTRAINT [UIWeaponsTypeCodeValue] UNIQUE NONCLUSTERED ([CodeValue] ASC) WITH (DATA_COMPRESSION = PAGE)
)
WITH (DATA_COMPRESSION = PAGE);

